#!/bin/sh
set -ex
git config --global user.email "automation@circleci.com"
git config --global user.name "CircleCI"
git checkout master
./run_tests
coverage html --include='pybitcoin/*'
rm -rf tmp.htmlcov
mv htmlcov tmp.htmlcov
git checkout gh-pages
rm -r htmlcov
mv tmp.htmlcov htmlcov
git add htmlcov || true
git commit -m"Automated test run by CircleCI - $(date)" || true
git push origin gh-pages
git checkout master
