"""initial

Revision ID: 197c134d68e9
Revises:
Create Date: 2015-11-22 14:27:34.646713

"""

# revision identifiers, used by Alembic.
revision = '197c134d68e9'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('block_hash', postgresql.BYTEA(length=32), nullable=False),
        sa.Column('version', sa.BigInteger(), nullable=False),
        sa.Column('prev_block_hash', postgresql.BYTEA(length=32), nullable=False),
        sa.Column('merkle_root', postgresql.BYTEA(length=32), nullable=False),
        sa.Column('timestamp', sa.BigInteger(), nullable=False),
        sa.Column('bits', sa.BigInteger(), nullable=False),
        sa.Column('nonce', sa.BigInteger(), nullable=False),
        sa.Column('prev_block_id', sa.Integer(), nullable=True),
        sa.Column('depth', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_block_hash'), 'block', ['block_hash'], unique=False)
    op.create_index(op.f('ix_block_id'), 'block', ['id'], unique=True)
    op.create_index('ix_block_prev_block_hash', 'block', ['prev_block_hash'], unique=False, postgresql_where=sa.text('block.prev_block_id IS NULL'))
    op.create_index(op.f('ix_block_prev_block_id'), 'block', ['prev_block_id'], unique=False)
    op.create_table('transaction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tx_hash', postgresql.BYTEA(length=32), nullable=False),
        sa.Column('version', sa.BigInteger(), nullable=False),
        sa.Column('lock_time', sa.BigInteger(), nullable=False),
        sa.Column('block_id', sa.Integer(), nullable=True),
        sa.Column('block_index', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['block_id'], ['block.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_block_id'), 'transaction', ['block_id'], unique=False)
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=True)
    op.create_index(op.f('ix_transaction_tx_hash'), 'transaction', ['tx_hash'], unique=False)
    op.create_table('txin',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('previous_output_transaction_hash', postgresql.BYTEA(length=32), nullable=False),
        sa.Column('previous_output_index', sa.BigInteger(), nullable=False),
        sa.Column('signature_script', sa.LargeBinary(), nullable=False),
        sa.Column('sequence', sa.BigInteger(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=True),
        sa.Column('transaction_index', sa.Integer(), nullable=False),
        sa.Column('txout_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_txin_id'), 'txin', ['id'], unique=True)
    op.create_index(op.f('ix_txin_transaction_id'), 'txin', ['transaction_id'], unique=False)
    op.create_index('ix_txin_tx_hash_idx', 'txin', ['previous_output_transaction_hash', 'previous_output_index'], unique=False, postgresql_where=sa.text('txin.txout_id IS NULL'))
    op.create_index(op.f('ix_txin_txout_id'), 'txin', ['txout_id'], unique=False)
    op.create_table('txout',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('value', sa.BigInteger(), nullable=False),
        sa.Column('pk_script', sa.LargeBinary(), nullable=False),
        sa.Column('to_address', sa.String(length=34), nullable=True),
        sa.Column('transaction_id', sa.Integer(), nullable=True),
        sa.Column('transaction_index', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_txout_id'), 'txout', ['id'], unique=True)
    op.create_index(op.f('ix_txout_to_address'), 'txout', ['to_address'], unique=False)
    op.create_index(op.f('ix_txout_transaction_id'), 'txout', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_txout_transaction_index'), 'txout', ['transaction_index'], unique=False)
    op.create_index('ix_txout_tx_id_idx', 'txout', ['transaction_id', 'transaction_index'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_txout_tx_id_idx', table_name='txout')
    op.drop_index(op.f('ix_txout_transaction_index'), table_name='txout')
    op.drop_index(op.f('ix_txout_transaction_id'), table_name='txout')
    op.drop_index(op.f('ix_txout_to_address'), table_name='txout')
    op.drop_index(op.f('ix_txout_id'), table_name='txout')
    op.drop_table('txout')
    op.drop_index(op.f('ix_txin_txout_id'), table_name='txin')
    op.drop_index('ix_txin_tx_hash_idx', table_name='txin')
    op.drop_index(op.f('ix_txin_transaction_id'), table_name='txin')
    op.drop_index(op.f('ix_txin_id'), table_name='txin')
    op.drop_table('txin')
    op.drop_index(op.f('ix_transaction_tx_hash'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_block_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_block_prev_block_id'), table_name='block')
    op.drop_index('ix_block_prev_block_hash', table_name='block')
    op.drop_index(op.f('ix_block_id'), table_name='block')
    op.drop_index(op.f('ix_block_block_hash'), table_name='block')
    op.drop_table('block')
    ### end Alembic commands ###
