"""change block_hash index to hash type

Revision ID: 3c7e64505f45
Revises: 59f5c554cf24
Create Date: 2015-11-22 15:56:18.241586

"""

# revision identifiers, used by Alembic.
revision = '3c7e64505f45'
down_revision = '59f5c554cf24'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_block_block_hash')
    op.create_index('ix_block_block_hash', 'block', ['block_hash'], postgresql_using='hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_block_block_hash')
    op.create_index('ix_block_block_hash', 'block', ['block_hash'])
    ### end Alembic commands ###
