"""add txout.spent

Revision ID: 444bc3ab78cf
Revises: 3c7e64505f45
Create Date: 2015-11-22 14:36:17.510637

"""

# revision identifiers, used by Alembic.
revision = '444bc3ab78cf'
down_revision = '3c7e64505f45'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('txout', sa.Column('spent', sa.Boolean(), server_default=sa.text(u'NULL'), nullable=True))
    op.create_index('ix_ixout_to_address_not_spent', 'txout', ['to_address'], unique=False, postgresql_using='hash', postgresql_where=sa.text(u'txout.spent IS false'))
    op.create_index(op.f('ix_txout_spent'), 'txout', ['spent'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_txout_spent'), table_name='txout')
    op.drop_index('ix_ixout_to_address_not_spent', table_name='txout')
    op.drop_column('txout', 'spent')
    ### end Alembic commands ###
