"""remove txin.previous_output columns

Revision ID: 4b1e45f9a329
Revises: 54b5822b18e5
Create Date: 2015-11-22 15:21:36.624010

"""

# revision identifiers, used by Alembic.
revision = '4b1e45f9a329'
down_revision = '54b5822b18e5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_txin_tx_hash_idx', table_name='txin')
    op.drop_column('txin', 'previous_output_index')
    op.drop_column('txin', 'previous_output_transaction_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('txin', sa.Column('previous_output_transaction_hash', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column('txin', sa.Column('previous_output_index', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_index('ix_txin_tx_hash_idx', 'txin', ['previous_output_transaction_hash', 'previous_output_index'], unique=False)
    ### end Alembic commands ###
