"""remove txin.txout_id and txout.spent

Revision ID: 50e8428da940
Revises: 5aa02878e393
Create Date: 2015-11-22 15:36:00.496105

"""

# revision identifiers, used by Alembic.
revision = '50e8428da940'
down_revision = '5aa02878e393'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_txin_txout_id', table_name='txin')
    op.drop_column('txin', 'txout_id')
    op.drop_index('ix_txout_spent', table_name='txout')
    op.drop_column('txout', 'spent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('txout', sa.Column('spent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_txout_spent', 'txout', ['spent'], unique=False)
    op.add_column('txin', sa.Column('txout_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_txin_txout_id', 'txin', ['txout_id'], unique=False)
    ### end Alembic commands ###
