"""change prev_block_hash index to hash type

Revision ID: 59f5c554cf24
Revises: 571f73096883
Create Date: 2015-11-22 15:51:34.084447

"""

# revision identifiers, used by Alembic.
revision = '59f5c554cf24'
down_revision = '571f73096883'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from pybitcoin import db


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_block_prev_block_hash')
    op.create_index('ix_block_prev_block_hash', 'block', ['prev_block_hash'], postgresql_where=db.Block.prev_block_id.is_(None), postgresql_using='hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_block_prev_block_hash')
    op.create_index('ix_block_prev_block_hash', 'block', ['prev_block_hash'], postgresql_where=db.Block.prev_block_id.is_(None))
    ### end Alembic commands ###
